baseURL = ""

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Lightstreams Documentation"
theme = "hugo-theme-docdock"
#themesdir = "../.."
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
contentDir = "./content"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
#
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"

[params]
editURL = "https://github.com/lightstreams-network/go-lightstreams/"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "flex"
themeVariant = "navy" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "github"
url = "https://github.com/lightstreams-network/cli-docs"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Docs</label>"
url = "https://wiki.lightstreams.network/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>HTTP API</label>"
identifier = "hugodoc"
url = "https://wiki.lightstreams.network/docs"
weight = 20
