#!/usr/bin/env bash

CMD_DOCS_FOLDER="auto_generated"

# find "${CMD_DOCS_FOLDER}/" -type f | \
# sed 's/auto_generated/content/' | \
# sed 's/\.md//' | \
# sed 's/_/\//g' | \
# xargs -exec -I % sh -c "mkdir -p %;"

# for f in auto_generated/*
# do
    #
# done


# ls auto_generated | sed 's/\.md//' | awk 'BEGIN{FS="_"}{print $2}'



for file in ${CMD_DOCS_FOLDER}/*
do
    folder=${file:0:-3}
    echo ${folder} | \
    sed 's/auto_generated/content\/04.cli-docs/' | \
    sed 's/_/\//g' | \
    xargs -exec -I % sh -c "mkdir -p %; cp ${file} %/_index.md"
done